
package cn.itcast.test.others.javaweb.testclass.webservice.jaxws.client.server;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://server.client.jaxws.webservice.testclass.javaweb.others.test.itcast.cn/")
public class Exception_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private cn.itcast.test.others.javaweb.testclass.webservice.jaxws.client.server.Exception faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Exception_Exception(String message, cn.itcast.test.others.javaweb.testclass.webservice.jaxws.client.server.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Exception_Exception(String message, cn.itcast.test.others.javaweb.testclass.webservice.jaxws.client.server.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cn.itcast.test.others.javaweb.testclass.webservice.jaxws.client.server.Exception
     */
    public cn.itcast.test.others.javaweb.testclass.webservice.jaxws.client.server.Exception getFaultInfo() {
        return faultInfo;
    }

}
