
package cn.itcast.test.others.javaweb.testclass.webservice.jaxws.client.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Weather", targetNamespace = "http://server.client.jaxws.webservice.testclass.javaweb.others.test.itcast.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Weather {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryWeather", targetNamespace = "http://server.client.jaxws.webservice.testclass.javaweb.others.test.itcast.cn/", className = "cn.itcast.test.others.javaweb.testclass.webservice.jaxws.client.server.QueryWeather")
    @ResponseWrapper(localName = "queryWeatherResponse", targetNamespace = "http://server.client.jaxws.webservice.testclass.javaweb.others.test.itcast.cn/", className = "cn.itcast.test.others.javaweb.testclass.webservice.jaxws.client.server.QueryWeatherResponse")
    public String queryWeather(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

}
